version: "3.8"

name: "event-booking-platform"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: event-booking-platform-backend
    ports:
      - "3081:3081"
    env_file:
      - backend/.env
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          ignore:
            - node_modules
          target: /app
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: event-booking-platform-db
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
