FROM node:lts-alpine

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

ENV NODE_ENV=development
ENV SERVER_PORT=3081

EXPOSE $SERVER_PORT

# TODO: This changes for production
CMD ["npm", "run", "dev"]
